alias: Ameren Update Pricing at midnight
description: ""
triggers:
  - trigger: time
    at: "00:01:00"
conditions: []
actions:
  - action: homeassistant.update_entity
    metadata: {}
    data:
      entity_id:
        - sensor.ameren_raw_data
        - sensor.ameren_raw_data_tomorrow
        - sensor.miso_raw_data_tomorrow
mode: single


alias: Ameren MISO Tomorrow Check Until Success
description: ""
triggers:
  - trigger: time_pattern
    minutes: /15
conditions:
  - condition: state
    entity_id: sensor.miso_raw_data_tomorrow
    state: unknown
  - condition: time
    after: "14:00:00"
actions:
  - action: homeassistant.update_entity
    data:
      entity_id:
        - sensor.miso_raw_data_tomorrow
mode: single


alias: Ameren Tomorrow Check until success
description: ""
triggers:
  - trigger: time_pattern
    minutes: /15
conditions:
  - condition: state
    entity_id: sensor.ameren_raw_data_tomorrow
    state: unknown
  - condition: time
    after: "18:00:00"
actions:
  - action: homeassistant.update_entity
    metadata: {}
    data:
      entity_id:
        - sensor.ameren_raw_data_tomorrow
        - sensor.ameren_raw_data
mode: single

